name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      GITHUB_ACTIONS: 'yes'
      PGPASSWORD: 'csvbase'

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: csvbase
          POSTGRES_PASSWORD: csvbase
          POSTGRES_DB: csvbase
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Write config file
      run: |
        cat <<EOF > ~/.csvbase.toml
        secret_key = "snakeoil"
        db_url = "postgresql+psycopg2://csvbase:csvbase@localhost/csvbase"
        stripe_api_key = "sample"
        stripe_price_id = "price_123"
        EOF
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install required ubuntu packages
      run: sudo apt-get update && sudo apt-get install -y libsystemd-dev postgresql-client
    - name: Create schemas
      run: psql -h localhost -d csvbase -U csvbase -f init-schemas.sql
    - name: Use cache of pip downloads
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install tox
      run: pip install tox
    - name: make static-deps
      run: make static-deps
    - name: Use cache of tox
      uses: actions/cache@v4
      with:
        path: .tox
        key: ${{ runner.os }}-tox
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Make
      run: make
